[versions]
kotlin = "2.3.0"
ktor = "3.3.3"
co-uzzu-dotenv-gradle = "4.0.0"
org-jlleitschuh-gradle-ktlint = "14.0.1"
jooq = "3.20.10"
flyway = "11.20.2"
logback = "1.5.25"
koin-ktor = "4.1.1"
io-r2dbc-r2dbc-pool = "1.0.2.RELEASE"
io-projectreactor-kotlin-reactor-kotlin-extensions = "1.3.0"
kotest = "6.1.1"
org-postgresql-postgresql = "42.7.9"
org-postgresql-r2dbc-postgresql = "1.1.1.RELEASE"
org-testcontainers-postgresql = "1.21.4"
org-assertj-assertj-db = "3.0.1"
jackson = "2.21.0"

[libraries]
org-flywaydb-flyway-database-postgresql = { group = "org.flywaydb", name = "flyway-database-postgresql", version.ref = "flyway" }
org-jooq-jooq = { group = "org.jooq", name = "jooq", version.ref = "jooq" }
org-jooq-jooq-kotlin = { group = "org.jooq", name = "jooq-kotlin", version.ref = "jooq" }
org-jooq-jooq-kotlin-coroutines = { group = "org.jooq", name = "jooq-kotlin-coroutines", version.ref = "jooq" }
org-jooq-jooq-meta = { group = "org.jooq", name = "jooq-meta", version.ref = "jooq" }
org-jooq-jooq-codegen = { group = "org.jooq", name = "jooq-codegen", version.ref = "jooq" }
ch-qos-logback-logback-classic = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }
io-insert-koin-koin-ktor = { group = "io.insert-koin", name = "koin-ktor", version.ref = "koin-ktor" }
io-insert-koin-koin-logger-slf4j = { group = "io.insert-koin", name = "koin-logger-slf4j", version.ref = "koin-ktor" }
io-r2dbc-r2dbc-pool = { group = "io.r2dbc", name = "r2dbc-pool", version.ref = "io-r2dbc-r2dbc-pool" }
io-projectreactor-kotlin-reactor-kotlin-extensions = { group = "io.projectreactor.kotlin", name = "reactor-kotlin-extensions", version.ref = "io-projectreactor-kotlin-reactor-kotlin-extensions" }
org-flywaydb-flyway-core = { group = "org.flywaydb", name = "flyway-core", version.ref = "flyway" }
io-kotest-kotest-runner-junit5 = { group = "io.kotest", name = "kotest-runner-junit5", version.ref = "kotest" }
io-kotest-kotest-assertions-core = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotest" }
io-kotest-kotest-assertions-json = { group = "io.kotest", name = "kotest-assertions-json", version.ref = "kotest" }
io-kotest-kotest-assertions-ktor = { group = "io.kotest", name = "kotest-assertions-ktor", version.ref = "kotest" }
io-kotest-kotest-extensions-testcontainers = { group = "io.kotest", name = "kotest-extensions-testcontainers", version.ref = "kotest" }
org-postgresql-postgresql = { group = "org.postgresql", name = "postgresql", version.ref = "org-postgresql-postgresql" }
org-postgresql-r2dbc-postgresql = { group = "org.postgresql", name = "r2dbc-postgresql", version.ref = "org-postgresql-r2dbc-postgresql" }
org-testcontainers-postgresql = { group = "org.testcontainers", name = "postgresql", version.ref = "org-testcontainers-postgresql" }
org-assertj-assertj-db = { group = "org.assertj", name = "assertj-db", version.ref = "org-assertj-assertj-db" }
io-ktor-ktor-server-core = { group = "io.ktor", name = "ktor-server-core" }
io-ktor-ktor-server-netty = { group = "io.ktor", name = "ktor-server-netty" }
io-ktor-ktor-server-content-negotiation = { group = "io.ktor", name = "ktor-server-content-negotiation" }
io-ktor-ktor-serialization-kotlinx-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json" }
io-ktor-ktor-server-request-validation = { group = "io.ktor", name = "ktor-server-request-validation" }
io-ktor-ktor-server-status-pages = { group = "io.ktor", name = "ktor-server-status-pages" }
io-ktor-ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation" }
io-ktor-ktor-server-test-host = { group = "io.ktor", name = "ktor-server-test-host" }
org-jetbrains-kotlin-kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
com-fasterxml-jackson-core-jackson-databind = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "jackson" }

[plugins]
org-jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
org-jetbrains-kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
io-ktor-plugin = { id = "io.ktor.plugin", version.ref = "ktor" }
co-uzzu-dotenv-gradle = { id = "co.uzzu.dotenv.gradle", version.ref = "co-uzzu-dotenv-gradle" }
org-jlleitschuh-gradle-ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "org-jlleitschuh-gradle-ktlint" }
org-jooq-jooq-codegen-gradle = { id = "org.jooq.jooq-codegen-gradle", version.ref = "jooq" }
org-flywaydb-flyway = { id = "org.flywaydb.flyway", version.ref = "flyway" }
jacoco = { id = "jacoco" }